# **Objetivo**

Preparar los datos para el análisis.

In [21]:
import pandas as pd
df = pd.read_csv( "FAMILIAS_FOCALIZADAS.csv" )

# Identificar valores nulos

In [22]:
df.isnull().sum()

Bancarizado                          58
CodigoDepartamentoAtencion            0
CodigoMunicipioAtencion               0
Discapacidad                          0
EstadoBeneficiario                    0
Etnia                                 0
FechaInscripcionBeneficiario          0
Genero                                0
NivelEscolaridad                      0
NombreDepartamentoAtencion            0
NombreMunicipioAtencion               0
Pais                                  0
TipoAsignacionBeneficio               0
TipoBeneficio                         0
TipoDocumento                         0
TipoPoblacion                         0
RangoBeneficioConsolidadoAsignado     0
RangoUltimoBeneficioAsignado          0
FechaUltimoBeneficioAsignado          0
RangoEdad                             0
Titular                               0
CantidadDeBeneficiarios               0
dtype: int64

# **Eliminar duplicados**

In [23]:
df.drop_duplicates( inplace=True )

# **Estandarizar nombres**

In [24]:
df.columns = ( df.columns .str.lower() .str.strip() .str.replace(" ", "_") )

# **Revisar categorías**

In [25]:
df["nombredepartamentoatencion"].value_counts()

nombredepartamentoatencion
BOYACA    1951
Name: count, dtype: int64

# **Guardar archivo limpio**

In [30]:
import os
from google.colab import files

output_dir = '../data/processed'

os.makedirs(output_dir, exist_ok=True)

file_name = 'familias_renta_ciudadana_clean.csv'
file_path = os.path.join(output_dir, file_name)

df.to_csv(file_path, index=False)

In [31]:
files.download(file_path)